### ISSUE TITLE
Mocking Functions

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#19]
**Recipient:** Degen Lab
**Bounty:** $34,200

## Project Approach

- **Objective**: Develop a comprehensive library for centralizing core Stacks boot functions for testing Clarity smart contracts.
- **Goals**:
    - Streamline testing by providing essential node functionalities without needing a stacks-node instance.
    - Enhance efficiency, consistency, and reliability in testing methodologies.
    - Include relevant data functions for Bitcoin-related tasks.

## Deliverables

1. **TypeScript Library**:
    - Mocked Stacks node functions for testing.
    - Functions for stacking contracts, general smart contracts, and Bitcoin-related operations.
2. **Testing**:
    - Extensive unit and integration tests to ensure library robustness.
    - Automated testing framework for maintaining quality standards.
3. **Documentation**:
    - Comprehensive documentation for each function.
    - Usage examples and a "Getting Started" guide.
4. **Automating Pipelines**:
    - Prepare library for publication.
    - Set up CI/CD pipeline for automated testing and releases.
    - Publish on npm for accessibility.
5. **Frontend User Interface**:
    - UX/UI Design.
    - Frontend development.

## Roadmap & Timeline

- **Milestone 1**: Stacks related functions (160 hours)
    - Mocking functions for stacking-related contracts.
    - Stacks utilities conversion to TypeScript.
- **Milestone 2**: Bitcoin related functions (110 hours)
    - Create helper wrappers for Bitcoin operations.
- **Milestone 3**: Testing and Refinement (96 hours)
    - Write and perform unit and integration tests.
- **Milestone 4**: Documentation (40 hours)
    - Create comprehensive documentation and a "Getting Started" guide.
- **Milestone 5**: Publication and Release (50 hours)
    - Prepare library for publication and set up CI/CD pipeline.

**Comment by BowTiedSirJonathan** [comment]
### Update on Mocking Functions Progress

**Milestone 1 - Stacks Related Functions: completed**
- Sprint 1 - Stacking Related Functions: All the stacking-related functions can be checked [here](https://github.com/degen-lab/stacks-testing-helpers/blob/master/src/functions/poxHelpers.ts)
- Sprint 2 - Stacks Utils: All the Stacks utils can be checked [here](https://github.com/degen-lab/stacks-testing-helpers/blob/master/src/functions/stacksUtils.ts)

**Milestone 2 - Bitcoin Related Functions: completed (PR opened)**
- Sprint 3 - Bitcoin Utils: All the Bitcoin utils can be checked [here](https://github.com/degen-lab/stacks-testing-helpers/blob/master/src/functions/bitcoinUtils.ts)

**Milestone 3 - Testing and Refinement: 75%**
- Sprint 4 - 3/4 TODOs related to testing are covered, considering the TDD (Test Driven Development) approach we followed for this project. We also decided to go beyond the initial testing plan, choosing property-based testing instead of unit testing where it was possible.

**Comment by BowTiedSirJonathan** [comment]
### Update on Mocking Functions Progress - Completed

**Milestone 3 - Testing and Refinement: Completed**
- **Sprint 4:** Developed testing for the library’s functions. Updated function and variable names to enhance functionality post-initial publication.

**Milestone 4 - Documentation: Completed**
- **Sprint 5:** Created comprehensive documentation explaining how to utilize the library, available on both the npm page and GitHub.

**Milestone 5 - Publication and Release: Completed**
- **Sprint 6:** Initially released the library for testing, followed by an official release on npm.

### [npm package](https://www.npmjs.com/package/stacks-testing-helpers)
### [github repo](https://github.com/degen-lab/stacks-testing-helpers)

@will-corcoran @shaktistacks

**Comment by will-corcoran** [comment]
This is great!  Thanks so much @BowTiedSirJonathan !  I will work with @shaktistacks to get the remainder of the bounty paid out to you.

**Comment by will-corcoran** [comment]
Hi @BowTiedSirJonathan 

We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will
