### ISSUE TITLE
Automation of Signer Delegations

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#20]
**Recipient:** Degen Lab
**Bounty:** $36,150

## Project Approach

- Create a Node.js app to automate `delegate-stack-stx` and `stack-aggregation-commit`/`stack-aggregation-increase` contract calls.
- During the reward phase, the app checks for valid delegations to a given STX address and processes them for the next cycle.
- Calls `delegate-stack-stx` for valid delegations and updates their status.
- Makes `stack-aggregation-commit` calls if the delegation sum exceeds the threshold, updating status based on transaction success.
- Handles new delegations in the last 15 blocks and prepares the database for the next cycle in the last 2 blocks.

## Deliverables

- **Deliverable 1**: Custom API endpoints and smart contract functions for data gathering and validation.
- **Deliverable 2**: Database to track delegations, simulate updates, and log states.
- **Deliverable 3**: Automated tool for smart contract calls, database updates based on transaction status.
- **Deliverable 4**: Comprehensive testing, including API, database operations, edge cases, and end-to-end testing.

## Roadmap & Timeline

- **Milestone 1**: Initial API endpoints and smart contract calls (5 weeks).
- **Milestone 2**: Database design and implementation (2 weeks).
- **Milestone 3**: Tool for automating delegation acceptance/commitment (1.6 weeks).
- **Milestone 4**: Comprehensive testing of all components (3 weeks).

**Comment by BowTiedSirJonathan** [comment]
### Update on Signer Flow Automation Progress

**Deliverable 1 - Initial API Endpoints and Smart Contract Calls: completed**
- Sprint 1 - Created the endpoint calls and structured the data [here](https://github.com/degen-lab/stacker-flow-automation-backend/commit/41ac8b1fe97b622a8ea73b5eb6a0cf7bb2c7300f)  
- Sprint 2 - Converted the results to JS values and optimized the initial application [here](https://github.com/degen-lab/stacker-flow-automation-backend/commit/41ac8b1fe97b622a8ea73b5eb6a0cf7bb2c7300f) 
 
**Deliverable 2 - Database to Track Data: completed**
- Sprint 3 - Created the database and structured the data [here](https://github.com/degen-lab/stacker-flow-automation-backend/commit/ad174fe578258a5c7c575b2500a5a81468cdd794)

**Deliverable 3 - Tool to Automate Accepting/Committing Delegations: completed**
- Sprint 4 - Combined previous flows, check and broadcast available contract calls [here](https://github.com/degen-lab/stacker-flow-automation-backend/commit/75fdab8b0efff6d2b6256420fdc282a6f7a1404a)

**Comment by BowTiedSirJonathan** [comment]
### Update on Signer Flow Automation Progress - Completed

**Milestone 4 - Comprehensive Testing of All Components: Completed**

- **Sprint 5:** API, Database and Edge Case Testing - ensure that base operations are being performed as expected [here](https://github.com/degen-lab/stacker-flow-automation/commit/5d712788dd385b88650a48dc891b81d6381c6700).
- **Sprint 6:** End-to-End Testing - simulate the flow in a close-to-mainnet scenario and check that the application is making the appropriate smart contract calls [here](https://github.com/degen-lab/stacker-flow-automation/commit/5d712788dd385b88650a48dc891b81d6381c6700).

**Milestone 5 - Front-End to Monitor the Status of Automated Operations: Completed**

- **Sprint 7:** Created an interactive front-end that pool operators can use in order to check  their stacking related information [here](https://github.com/degen-lab/stacker-flow-automation/tree/main/frontend).

The project’s work has been consolidated into a single repository to make it more dev-friendly. 

### [github repo](https://github.com/degen-lab/stacker-flow-automation) 

@will-corcoran @shaktistacks

**Comment by will-corcoran** [comment]
This is great!  Thanks so much @BowTiedSirJonathan !  I will work with @shaktistacks to get the remainder of the bounty paid out to you.

**Comment by will-corcoran** [comment]
Hi @BowTiedSirJonathan 

We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will
